package GUI;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OpenPanel.java
 *
 * Created on Jan 26, 2009, 1:13:17 PM
 */


import java.io.File;
import javax.swing.JDialog;

/**
 *
 * @author joe
 */
public class OpenPanel extends javax.swing.JPanel
{
    MainFrame data;
    private int type;
    public static final int OPEN_FILE = 0;
    public static final int IMPORT = 1;
    public static final int SAVE = 2;
    

    /** Creates new form OpenPanel
     * @param data
     * @param type
     */
    public OpenPanel(MainFrame data, int type)
    {
        this.type = type;
        this.data = data;

        initComponents();
        
        fileChooser.setCurrentDirectory(new File("%USERPROFILE%/Desktop"));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();

        fileChooser.setCurrentDirectory(new File("%USERPROFILE%/Desktop"));
        fileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(fileChooser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(fileChooser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fileChooserActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fileChooserActionPerformed
    {//GEN-HEADEREND:event_fileChooserActionPerformed
        if (evt.getActionCommand().equals("CancelSelection"))
        {
            ((JDialog) this.getTopLevelAncestor()).dispose();
        }
        else if (fileChooser.getSelectedFile().getAbsolutePath().equals(null))
        {
        }
        else
        {
            if(type == OPEN_FILE)
            {
                data.filePath  = fileChooser.getSelectedFile().getAbsolutePath();
                data.load();
            }
            else if(type == IMPORT)
            {
                String path = fileChooser.getSelectedFile().getAbsolutePath();
                data.importPlayers(path);
            }
            else
            {

            }
            ((JDialog) this.getTopLevelAncestor()).dispose();
        }
}//GEN-LAST:event_fileChooserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fileChooser;
    // End of variables declaration//GEN-END:variables

}
